version: '3.0'

services:
  nginx:
    image: nginx:1.16.0-alpine
    depends_on:
      - db
    volumes:
      - $PWD/nginx:/etc/nginx:ro
      - ./cogip-src:/var/www/html
    ports:
      - '80:80'
    networks:
      - frontend
  db:
    image: mariadb
    restart: always
    env_file: $PWD/.env.database
    networks:
      - backend
    volumes:
      - $PWD/cogip-src/database:/docker-entrypoint-initdb.d
      - $PWD/db:/var/lib/mysql 
  
  cogip_php:
#    image: php:7.4-fpm
    image: php:7.4-fpm-mysql
    build:
      dockerfile: Dockerfile.php
    depends_on:
      - db
    volumes:
      - ./cogip-src:/var/www/html
    networks:
      - frontend
      - backend

networks:
  frontend:
  backend:

