- name: check for database
  mysql_db:
    name: '{{ db_name }}'
    login_user: '{{ db_username }}'
    login_password: '{{ db_password }}'
    state: present
  register: database_exists

- name: check variable
  debug:
    msg: '{{ database_exists }}'

- name: create database
  mysql_db:
    name: '{{ db_name }}'
    state: present
  when: database_exists.db != 'cogip'

- name: run init script
  mysql_db:
    state: import
    name: '{{ db_name }}'
    login_user: '{{ db_username }}'
    login_password: '{{ db_password }}'
    #encoding: latin1
    target: '{{ db_init_path }}'
  when: database_exists.changed

- name: Create users
  mysql_query:
    login_db: '{{ db_name }}'
    login_host: localhost
    login_user: '{{ db_username }}'
    login_password: '{{ db_password }}'
    query: INSERT INTO user (username,password,mode) VALUES (%(username),%(password),%(mode))
    named_args:
      username: '{{ item.username }}'
      password: '{{ item.password }}'
      mode: '{{ item.mode }}'
  loop: '{{ db_users }}'
