- name: Run the equivalent of "apt-get update" as a separate step
  apt:
    update_cache: yes

- name: Update all packages to their latest version
  apt:
    name: '*'
    state: latest

- name: install python deps
  apt:
    name: '{{ db_python_deps }}'
    state: present

- name: Check for existing mysql installation
  stat: path='/etc/init.d/{{ mysql_daemon }}'
  register: mysql_installed

- name: install mysql
  apt:
    name: '{{ db_packages }}'
    update_cache: yes
  when: not mysql_installed.stat.exists

- name: start up the mysql service
  shell: 'service mysql start'

- name: ensure mysql is enabled to run on startup
  service: name=mysql state=started enabled=true

- name: Create db_user
  mysql_user:
    name: '{{ db_username }}'
    host: '{{ db_host }}'
    password: '{{ db_password }}'
    priv: '*.*:ALL,GRANT'
    state: present
# - name: Update MySQL root password for localhost root account (< 5.7.x).
#   shell: >
#     mysql -NBe
#     'SET PASSWORD FOR "{{ mysql_root_username }}"@"{{ item }}" = PASSWORD("{{ mysql_root_password }}"); FLUSH PRIVILEGES;'
#   with_items: "{{ mysql_root_hosts.stdout_lines|default([]) }}"
#   when: >
#     ((mysql_install_packages | bool) or mysql_root_password_update)
#     and ('5.7.' not in mysql_cli_version.stdout and '8.0.' not in mysql_cli_version.stdout)
