- name: Remove default server conf file
  file:
    path: /etc/nginx/sites-enabled/default
    state: absent

- name: Install nginx config
  template:
    src: '{{ role_path }}/templates/nginx/conf.d/cogip.conf.j2'
    dest: '{{ web_server_conf_path }}/conf.d/cogip.conf'
    mode: 0644
  notify:
    - restart nginx
# - name: Install .htpasswd
#   template:
#     src: "{{ role_path }}/templates/nginx/matrix-synapse-metrics-htpasswd.j2"
#     dest: "{{ matrix_nginx_proxy_data_path }}/matrix-synapse-metrics-htpasswd"
#     owner: "{{ matrix_user_username }}"
#     group: "{{ matrix_user_groupname }}"
#     mode: 0400
#   when: "matrix_nginx_proxy_proxy_synapse_metrics_basic_auth_enabled|bool and matrix_nginx_proxy_proxy_synapse_metrics|bool"

# - name: 'Change owner of site source to www-data'
#   file:
#     path: '{{ site_web_path }}'
#     state: directory
#     recurse: yes
#     owner: '{{ nginx-user }}'
#     group: '{{ nginx-group }}'
