---
site_web_path: '/var/www/cogip'
web_server_conf_path: '/etc/nginx'
db_init_path: '{{site_web_path}}/database/{{ db_init_script}}'
db_init_script: cogip.sql
db_name: 'cogip'
db_host: 'localhost'
db_password: 'root'
nginx-user: 'www-data'
nginx-group: 'www-data'
db_python_deps: python3-mysqldb
db_packages:
  #  - MySQL-python
  - mysql-common
  - mysql-server
