---
site_web_path: '/var/www/cogip'
web_server_conf_path: '/etc/nginx'

######
# DB #
######

db_init_path: '{{site_web_path}}/database/{{ db_init_script}}'
db_init_script: cogip.sql
db_python_deps:
  - python3-mysqldb
  - python-pymysql
db_packages:
  #  - MySQL-python
  - mysql-common
  - mysql-server
mysql_daemon: mysql

db_host: 'localhost'
db_username: 'root'
db_password: 'root'
db_name: 'cogip'
db_root_password: root

db_users:
  - { username: 'admin', password: 'admin123', mode: 'winner' }
  - { username: 'test', password: 'test', mode: 'not-winner' }

nginx-user: 'www-data'
nginx-group: 'www-data'
